### ISSUE TITLE
java从数据库一次性查询出100w条数据放入list,放不下的吧

### ISSUE THREAD

**Issue by DreamCartier** [550690513/large-amount-data-export#1]
你好，我想问下，你们是一次性查询出100w的数据量吗，还是分页导出的，如果是分页导出，能否告知下代码

**Comment by 550690513** [comment]
不好意思,由于前段时间成都出差,今天才抽出时间看了下.针对你的问题,我在代码中补充了部分注释以解答,希望能帮到你.另一点需要说明的是:模拟的100W条数据是存放在com.alibaba.fastjson(号称第一快json解析)的JSONArray数组中,而非存放在list当中,程序运行的时候这些数据是存放在内存中,导出速度也和电脑配置有关;xlsx的最大支持行数为1048576行,至于一次性导出还是分页,在功能实现上是没有问题的,需要根据自己的项目需求来定.

**Comment by DreamCartier** [comment]
anyway,thank you

**Comment by xiaopohou** [comment]
你好哥们，很高兴能看到您的分享，我今天测试一下你的代码，我循环100万数据，excel列 13列，运行的时候非常慢，跟你的测试报告数据不一致！

**Comment by xiaopohou** [comment]
@550690513

补充一下，我分段计时，我刚才构造了100数据耗时13秒，然后再去生成excel,几乎不动了！
